# Generated by Django 5.1.7 on 2025-03-25 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('diseaseID', models.AutoField(primary_key=True, serialize=False)),
                ('diseaseName', models.CharField(max_length=255, unique=True)),
                ('symptoms', models.JSONField()),
                ('treatment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Diagnoses',
            fields=[
                ('diagnosisId', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('doctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses_as_doctor', to=settings.AUTH_USER_MODEL)),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses_as_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosisId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiseaseManagement.diagnoses')),
                ('diseaseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiseaseManagement.diseases')),
            ],
        ),
    ]
