# Generated by Django 5.1.7 on 2025-03-30 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('biological_sex', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('role', models.IntegerField(choices=[(0, 'Patient'), (1, 'Doctor'), (2, 'Admin')], default=0)),
                ('specialty', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('reason', models.TextField()),
                ('doctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_of_doctor', to='UserManagement.users')),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_of_patient', to='UserManagement.users')),
            ],
        ),
    ]
