# Generated by Django 5.1.7 on 2025-03-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('biological_sex', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('role', models.IntegerField(choices=[(0, 'Patient'), (1, 'Doctor'), (2, 'Admin')], default=0)),
                ('specialty', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
