# Generated by Django 5.1.7 on 2025-03-31 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointments',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
