# Generated by Django 5.1.7 on 2025-03-25 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('reason', models.TextField()),
                ('doctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_of_doctor', to='UserManagement.users')),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_of_patient', to='UserManagement.users')),
            ],
        ),
    ]
