services:
  - type: web
    name: django-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings
      - key: SECRET_KEY
        value: <tạo_secret_key>
      - key: DEBUG
        value: False