"""
Django settings for hospital_web project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import os
import dj_database_url

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR =os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TEMPLATE_DIR = os.path.join(BASE_DIR,'hospital') 


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+%70bj&(=plk%op)2203yngsoseidf#0rg6*ytz@u65bk9f2^+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'django.contrib.sites',  # Required for allauth
    'allauth', # Required for allauth
    'allauth.account', # Required for allauth
    'allauth.socialaccount', # Required for allauth
    'allauth.socialaccount.providers.google',  # Google oauth2
    'hospitalManagement', 
    'widget_tweaks',
    'rest_framework', 
    'corsheaders',
    
]
AUTH_USER_MODEL = 'hospitalManagement.CustomUser'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'corsheaders.middleware.CorsMiddleware'
]

CORS_ALLOW_ALL_ORIGINS = True
ROOT_URLCONF = 'hospital_web.urls'
CSRF_TRUSTED_ORIGINS = [
    'https://deep-urchin-plainly.ngrok-free.app',
    'https://lekhoiblog.id.vn',
    # Thêm các domain khác nếu cần, ví dụ domain production của bạn sau này
    # 'https://your-production-domain.com',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR,],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hospital_web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'defaultdb',
        'USER': 'avnadmin',
        'PASSWORD': 'AVNS_Dd8AN4gnRm2cET54DAH',
        'HOST': 'test-gm-57fa.f.aivencloud.com',
        'PORT': '10290',
        'OPTIONS': {
            'sslmode': 'require',  # Required for Aiven
        },
    }
}

OPENAI_API_KEY = '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'
HUGGINGFACE_API_TOKEN = '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'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Asia/Bangkok"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
MEDIA_ROOT = os.path.join(BASE_DIR, 'hospital', 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/afterlogin/'
LOGOUT_REDIRECT_URL = '/'

 #--------------------------allauth setup & google calendar
SESSION_ENGINE = "django.contrib.sessions.backends.db"
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend'
]
SITE_ID = 1  # Required by django-allauth
SITE_URL = 'http://127.0.0.1:8000'  # Used for building redirect_uri



# Set a secure session cookie
SESSION_COOKIE_SECURE = False  # Set to False only in local development
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'  # 'Strict' may block OAuth redirects
SESSION_COOKIE_AGE = 15 * 60
SECURE_SSL_REDIRECT = False
CSRF_COOKIE_SECURE = False
#------------------------------------------------

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWS_CREDENTIALS = True
# AUTH_USER_MODEL = 'UserManagement.Users'

#OTP
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'giangcam2005@gmail.com'
EMAIL_HOST_PASSWORD = 'fups hspf fems wlje'

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'