# Generated by Django 5.1.7 on 2025-03-31 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('diseaseID', models.AutoField(primary_key=True, serialize=False)),
                ('diseaseName', models.CharField(max_length=255, unique=True)),
                ('symptoms', models.TextField()),
                ('treatment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientDischargeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('patientName', models.CharField(max_length=40)),
                ('assignedDoctorName', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('symptoms', models.CharField(max_length=100, null=True)),
                ('admitDate', models.DateField()),
                ('releaseDate', models.DateField()),
                ('daySpent', models.PositiveIntegerField()),
                ('roomCharge', models.PositiveIntegerField()),
                ('medicineCost', models.PositiveIntegerField()),
                ('doctorFee', models.PositiveIntegerField()),
                ('OtherCharge', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=11)),
                ('biological_sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnoses',
            fields=[
                ('diagnosisId', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('doctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses_as_doctor', to=settings.AUTH_USER_MODEL)),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses_as_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosisId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalManagement.diagnoses')),
                ('diseaseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalManagement.diseases')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/DoctorProfilePic/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('department', models.CharField(choices=[('bac_si_tim_mach', 'Bác sĩ Tim mạch'), ('bac_si_da_lieu', 'Bác sĩ Da liễu'), ('bac_si_cap_cuu', 'Bác sĩ Cấp cứu'), ('bac_si_di_ung_mien_dich', 'Bác sĩ Dị ứng/ Miễn dịch'), ('bac_si_gay_me', 'Bác sĩ Gây mê'), ('bac_si_ngoai_tieu_hoa', 'Bác sĩ Ngoại tiêu hóa')], default='bac_si_tim_mach', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('admitDate', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('symptoms', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointmentID', models.AutoField(primary_key=True, serialize=False)),
                ('patientName', models.CharField(max_length=40, null=True)),
                ('doctorName', models.CharField(max_length=40, null=True)),
                ('appointmentDate', models.DateField(auto_now=True)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('doctorId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='hospitalManagement.doctor')),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='hospitalManagement.patient')),
            ],
        ),
    ]
