# Generated by Django 5.1.7 on 2025-04-07 08:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('times_per_day', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pic/')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('nam', 'Nam'), ('nu', 'Nữ')], max_length=10, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('multi_factor_enabled', models.BooleanField(default=False)),
                ('ip_address_last_login', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_set', related_query_name='customuser', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_permissions', related_query_name='customuser', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, choices=[('bac_si_tim_mach', 'Bác sĩ Tim mạch'), ('bac_si_da_lieu', 'Bác sĩ Da liễu'), ('bac_si_khoa_noi', 'Bác sĩ Nội Tổng quát'), ('bac_si_khoa_ngoai', 'Bác sĩ Ngoại Tổng quát'), ('bac_si_di_ung_mien_dich', 'Bác sĩ Dị ứng/ Miễn dịch'), ('bac_si_gay_me', 'Bác sĩ Gây mê'), ('bac_si_tai_mui_hong', 'Bác sĩ Tai Mũi Họng'), ('bac_si_nhi_khoa', 'Bác sĩ Nhi khoa'), ('bac_si_phu_san', 'Bác sĩ Phụ sản'), ('bac_si_tieu_duong', 'Bác sĩ Tiểu đường'), ('bac_si_tieu_hoa', 'Bác sĩ Tiêu hóa'), ('bac_si_x_quang', 'Bác sĩ X-quang'), ('bac_si_phau_thuat', 'Bác sĩ Phẫu thuật'), ('bac_si_tam_ly', 'Bác sĩ Tâm lý'), ('bac_si_khoa_hoc', 'Bác sĩ Khoa học'), ('bac_si_khoa_khac', 'Bác sĩ Khoa khác')], max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AI_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('record_date', models.DateField()),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('glucose', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('liver_enzymes', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cretinine', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('acid_uric', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cholesterol', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_record', to='hospitalManagement.patient')),
            ],
            options={
                'verbose_name': 'AI Record',
                'verbose_name_plural': 'AI Records',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentDate', models.DateField()),
                ('appointmentTime', models.TimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service', to='hospitalManagement.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service', to='hospitalManagement.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('record_date', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='hospitalManagement.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='hospitalManagement.patient')),
                ('service', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitalManagement.service')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitalManagement.medicine')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalManagement.service')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('release_time', models.TimeField(blank=True, null=True)),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('pay_time', models.TimeField(blank=True, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.BooleanField(default=False)),
                ('method', models.CharField(blank=True, max_length=50, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalManagement.patient')),
                ('service', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitalManagement.service')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, choices=[('online', 'Tư vấn online'), ('offline', 'Khám bệnh trực tiếp')], max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='hospitalManagement.service')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('liver_enzymes', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cretinine', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('acid_uric', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cholesterol', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalManagement.service')),
            ],
        ),
    ]
