# Generated by Django 5.1.7 on 2025-03-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='assignedDoctorId',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='symptoms',
        ),
    ]
