# Generated by Django 5.1.7 on 2025-04-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='status',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
