# Generated by Django 5.1.7 on 2025-04-01 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctorName',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patientName',
        ),
    ]
