# Generated by Django 5.1.7 on 2025-06-06 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('blood', 'Máu'), ('urine', 'Nước tiểu'), ('cancer', 'Ung thư'), ('other', 'Khác')], max_length=20)),
                ('custom_test_name', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='test_results/')),
                ('test_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('test_place', models.CharField(blank=True, max_length=100, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_test_results', to='hospitalManagement.patient')),
            ],
        ),
    ]
