# Generated by Django 5.1.7 on 2025-04-02 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='phone_number',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='biological_sex',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointmentTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmentDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('bac_si_tim_mach', 'Bác sĩ Tim mạch'), ('bac_si_da_lieu', 'Bác sĩ Da liễu'), ('bac_si_cap_cuu', 'Bác sĩ Cấp cứu'), ('bac_si_di_ung_mien_dich', 'Bác sĩ Dị ứng/ Miễn dịch'), ('bac_si_gay_me', 'Bác sĩ Gây mê'), ('bac_si_tai_mui_hong', 'Bác sĩ Tai Mũi Họng')], default='bac_si_tim_mach', max_length=50),
        ),
        migrations.CreateModel(
            name='timeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeSlot', models.TimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('appointmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeSlots', to='hospitalManagement.appointment')),
            ],
        ),
    ]
