# Generated by Django 5.1.7 on 2025-04-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalManagement', '0002_remove_admin_status_remove_doctor_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
