# Generated by Django 5.1.7 on 2025-04-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalManagement', '0003_remove_patient_symptoms_appointment_doctorname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointmentTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmentDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
