# Generated by Django 5.1.7 on 2025-04-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalManagement', '0003_patient_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='about',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
