# Generated by Django 5.1.7 on 2025-04-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalManagement', '0004_doctor_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('bac_si_tim_mach', 'Bác sĩ Tim mạch'), ('bac_si_da_lieu', 'Bác sĩ Da liễu'), ('bac_si_khoa_noi', 'Bác sĩ Nội Tổng quát'), ('bac_si_khoa_ngoai', 'Bác sĩ Ngoại Tổng quát'), ('bac_si_di_ung_mien_dich', 'Bác sĩ Dị ứng/ Miễn dịch'), ('bac_si_gay_me', 'Bác sĩ Gây mê'), ('bac_si_tai_mui_hong', 'Bác sĩ Tai Mũi Họng'), ('bac_si_nhi_khoa', 'Bác sĩ Nhi khoa'), ('bac_si_phu_san', 'Bác sĩ Phụ sản'), ('bac_si_tieu_duong', 'Bác sĩ Tiểu đường'), ('bac_si_tieu_hoa', 'Bác sĩ Tiêu hóa'), ('bac_si_x_quang', 'Bác sĩ X-quang'), ('bac_si_phau_thuat', 'Bác sĩ Phẫu thuật'), ('bac_si_tam_ly', 'Bác sĩ Tâm lý'), ('bac_si_khoa_hoc', 'Bác sĩ Khoa học'), ('bac_si_khoa_khac', 'Bác sĩ Khoa khác')], default='bac_si_tim_mach', max_length=50),
        ),
    ]
